### ISSUE TITLE
Property 'create' is missing in type 'AsyncBackend'

### ISSUE THREAD

**Issue by ChrisZieba** [Widen/i18next-async-backend#2]
![Screenshot from 2021-05-06 00-11-57](https://user-images.githubusercontent.com/2230570/117256699-da8ef600-adff-11eb-8cbf-51e1a27bcab4.png)

```
Class 'AsyncBackend' incorrectly implements interface 'BackendModule<AsyncBackendOptions>'.
  Property 'create' is missing in type 'AsyncBackend' but required in type 'BackendModule<AsyncBackendOptions>'.

11 export default class AsyncBackend
```

**Comment by mskelton** [comment]
So sorry for the delay in responding.  This package is designed for i18next version 20+ and it looks like you are using i18next version 19 which is why the type issue is occurring.  If you update your i18next version this issue will be fixed.
